[position]
anchor = "top-right"
x = 0
y = 0

[images]
odd = "images/odd.png"
even = "images/even.png"
neutral = "images/neutral.png"
width = 400
height = 250

[images.keys]
KEY_ENTER = "images/enter.png"
"Shift+KEY_1" = "images/exclamation.png"
"Shift+KEY_SLASH" = "images/question.png"
